### PR TITLE
Address TRAC-395 and TRAC-396.

### PR DESCRIPTION
**Pull request by markpbaggett**
**JIRA Ticket**: [TRAC-395](https://jira.lib.utk.edu/browse/TRAC-395)

# What does this Pull Request do?
This PR does some refactoring with names in order to integrate ORCID iDs.

# What's new?
* New README with repo structure.
* Names have been totally refactored to be more flexible.
* Orcid blanks exists for all name.s

# How should this be tested?

Import the form and associate it to test.  Form builder is stripping some content on export, so it's a good idea to test all fields if you're not reading the diff carefully.

# Additional Notes:
This does not wrap up the ticket.  There is some refactoring to be done, but getting this merged will gurantee it gets in tomorrow's build.

# Interested parties
@CanOfBees

### CODE REVIEW

**Comment by markpbaggett** [comment]
@CanOfBees One more note:  I changed the XSD to 3.5, but it doesn't appear the XSD is getting into the final output.  I suggest testing this as well before merge.

**Comment by markpbaggett** [comment]
@CanOfBees, also, can you **squash and merge** when you merge instead of just merging?  It'd probably be neater to get into that habit.

**Comment by CanOfBees** [comment]
Looks good but XSD isn't showing. Needs to be added as a hidden attribute field on the root element.

**Comment by markpbaggett** [comment]
Cool.  I'll fix the XSD issue and push.

**Comment by markpbaggett** [comment]
@CanOfBees K.  Let me know if that's good.

**Comment by CanOfBees** [comment]
@markpbaggett could you update the xsi:schemaLocation to the following value: `http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd`? 

Edit: apologies, gave the wrong xsd URL

**Comment by markpbaggett** [comment]
@CanOfBees, Ugh!  That was me, not you.  Also, as you mentioned on HipChat, I notice the other attributes on root are getting dropped as well.  I'll fix those too.

**Comment by markpbaggett** [comment]
@CanOfBees, Since this just screws us metadata wise (not form appearance wise), let's create a separate ticket so we can merge and get this into the build. I'll fix the xsd again then push, test, and squash. I'll also create the ticket.

**Comment by markpbaggett** [comment]
Creating Trac-400 so this can be merged.

**Pull request merged**
