### PR TITLE
Phoenix

### PR DESCRIPTION
**Pull request by mlhale7**
**JIRA Ticket**: [CON-22](https://jira.lib.utk.edu/browse/CON-22)

# What does this Pull Request do?

This pull request adds an Islandora form for the Phoenix digital collection - https://digital.lib.utk.edu/collections/islandora/object/collections%3Aphoenix

# How should this be tested?

- Create a record using the form
- Update a record*
- Check for any inconsistencies in the resulting XML, including empty nodes

*Updating a record causes an issue with the subject tab panel. When a record is updated, it automatically adds the same number of subjects panes as was added in the initial record. I've added a blank field ("-") in the selection pane so the added subjects are easy to identify. I'm uncertain if this can be fixed.

# Additional Notes:
Currently I have a placeholder in the ISSN field ("XXXX-XXXX"). An ISSN has been applied for for this digitized version of the magazine, but it will not be available for at least a month.

# Interested parties
@markpbaggett 
@CanOfBees

### CODE REVIEW

**Comment by CanOfBees** [comment]
@mlhale7 taking a look at this now

**Review by CanOfBees — COMMENTED** [review]
@mlhale7 aside from the problem you mentioned re updating(/READ) this works fine. 

I had a thought re the READ for `mods:subject/mods:topic`s: we could provide attribute values in a separate file, and insert them in the MODS as part of the post-process transform. We did something very similar for ETDs, so while I'm not 100% sure how it would look, it might be worth trying. The thought was that it might simplify the READ process (i.e. get rid of some of those `not(...)`s) and make that part easier to fix.

**Comment by mlhale7** [comment]
@CanOfBees - thanks for this. Is the update issue with tab panels a known issue within the Islandora community or would it be helpful to reach out to a listserv? We really aren't planning on using these forms past initial metadata creation, but it's still possible that people could create a mess with it. If it's easy to put the subject URIs into a post-process transform, that makes a lot of sense to me as it would simplify the entry process. I've updated the form so these are no longer present and I'll create a ticket in JIRA. Let me know your thoughts.

**Comment by CanOfBees** [comment]
@mlhale7 re `Is the update issue with tab panels a known issue within the Islandora community or would it be helpful to reach out to a listserv?`: I'm not 100% sure - however, I know we have update (READ operations) working correctly in other forms that are using the same fieldpanel layout. My initial impression was that it might be related to having the hidden fields combined with the selectors on topics and valueURis *but!* there's a very (very very very) good chance that I'm wrong about that. 

Edit: so, I'm wrong about this (talked /w @markpbaggett and he reminded me about the problem): there is a bug in the fieldpanel stuff. It might be easiest to try implementing using tabpanels - are you opposed to that?

**Comment by CanOfBees** [comment]
@mlhale7 try to diff against [this gist](https://gist.github.com/CanOfBees/0da725751598c0290b10431d32a63dc9) (many thanks to @markpbaggett for getting this right)

**Comment by mlhale7** [comment]
@CanOfBees - I'll keep looking into this, but the same issue also exists with tab panels (see image - added three initially and got six subjects on updating). tabs_update
I can see that you are handling the path very generically for the panel (just mods:topic). I'm including valueURIs to exclude the three blanket URIs I've included in the form from getting updated (since they also have an xpath of mods/subject/topic). Let me know if this is unnecessary.

**Comment by CanOfBees** [comment]
@mlhale7 sorry for the confusion. If I'm thinking about this correctly, you want to match at the subject level (e.g. at `mods:subject[\@with-your-valueURIs-articulated-here]). Moving those predicates fixes this behavior - try importing [this gist](https://gist.github.com/CanOfBees/0da725751598c0290b10431d32a63dc9) and check the difference after importing/associating the form.

working-fieldpanel

**Comment by mlhale7** [comment]
@CanOfBees - I remembered that we talked on Friday about tabs and said that fieldpanels are actually fine. Apologies for the confusion. Your suggestions make this form work correctly. The only difference between our files should be that there is just one fieldpanel in mine (there are two in yours). I really appreciate all of your thoughtful comments on this. Let me know if there are additional issues to address before merging.

**Comment by mlhale7** [comment]
You are thinking correctly about the subject level match - I was confused.

**Comment by mlhale7** [comment]
@CanOfBees - I changed the ISSN placeholder to the actual number (now that we actually have it) and added back in the valueURIs. Let me know if you have any questions. Thanks!

**Comment by CanOfBees** [comment]
@mlhale7 taking a look now.

**Review by CanOfBees — APPROVED** [review]
@mlhale7 This looks great - thanks for your work on this.

**Comment by CanOfBees** [comment]
Approved and merging.

**Pull request merged**
