### PR TITLE
Trac 946

### PR DESCRIPTION
**Pull request by CanOfBees**
**JIRA Ticket**: [TRAC-946](https://jira.lib.utk.edu/browse/TRAC-946)

# What does this Pull Request do?
1. This PR adds a data file to simplify processing disciplines, departments, and colleges.
2. This PR adds template rules to the ETDS post-processing transform to handle new elements (mods:affiliation), populating and/or copying them as appropriate.

# What's new?
1. trace-disciplines-list-comp.xml: a list of all disciplines, with their respective departments and colleges; e.g. `<entry college="College of Arts and Sciences" dept="English" discipline="English"/>`
2. UTK_ir_etds_post_process.xsl: new templates for processing 6 new `mods:affiliation` elements, populating and/or copying them as appropriate. See notes in the [utk_gradthes Data Dictionary](https://wiki.lib.utk.edu/pages/viewpage.action?pageId=17727665).

# How should this be tested?
1. destroy, update, and `vagrant up` your Trace VM
2. after your VM is up, ssh into it
3. ensure that this branch (TRAC-946) is available in the git repository `/home/vagrant/utk_isl_xml_forms` and `git checkout` the branch; e.g. `git checkout -b TRAC-946 origin/TRAC-946`
4. in `/home/vagrant`, `curl` the following php script: `https://gist.githubusercontent.com/CanOfBees/5a02b2d6b68cb43416ea0a424102c5b3/raw/dbff403ed9842600404fdebfefcbd45bd853dbd7/php-exslt-test.php`; e.g. `curl -O https://gist.githubusercontent.com/CanOfBees/5a02b2d6b68cb43416ea0a424102c5b3/raw/dbff403ed9842600404fdebfefcbd45bd853dbd7/php-exslt-test.php`
5. grab a copy of a sample metadata record: `curl -o utk_isl_xml_forms/test_data/test-mods.xml https://gist.githubusercontent.com/CanOfBees/f80306ad9a2d2ef20a9c29b825724414/raw/0a19937653cb9b81e2edd4bbbf7354c339b89a18/test-mods.xml`
6. execute the php script that was downloaded earlier; `sudo php php-exslt-test.php`
7. review the output in `/vagrant/test-mods-out.xml`

# Additional Notes:
Keep in mind that values (particularly `/mods/extension/degree/discipline`) drive what happens with processing affiliations 1,2,5, and 6. Test with a value from the discipline entries in `trace-disciplines-list-comp.xml` and then with a value that doesn't appear there.

Additionally, some of the functionality should help with us when we need to write a datasets post-processing transform; e.g. affiliations 3 and 4.

Additionally part II, there will need to be some changes to our deployment scripts for the Trace VM and we'll need to be sure that these files make their way over to the live server.

Thanks for your reviews and feedback!
# Interested parties
@cdeaneGit @markpbaggett

### CODE REVIEW

**Review by cdeaneGit — COMMENTED** [review]
I followed steps 1 through 7 and all was well. The code in /vagrant/test-mods-out.xml was fine.

But then I logged in to localhost() as userA and submitted a gradthes.  After filling out the form, the next page showed the following warning message:

Warning: XSLTProcessor::transformToDoc(): I/O warning : failed to load external entity "/var/www/drupal/sites/all/modules/islandora_xml_forms/builder/self_transforms/trace-disciplines-list-comp.xml" 
in xml_form_builder_transform_metadata_datastream() (line 611 of /var/www/drupal/sites/all/modules/islandora_xml_forms/builder/xml_form_builder.module). 

 I repeated steps 1-7 a second time to make sure I had follwed everything in order.  The result was the same.

I need to discuss my testing procedure with Bridger.

**Review by cdeaneGit — APPROVED** [review]
I restested starting with a newly minted branch of TRACE(TRAD-685).  I was previeously testing on TRACE(TRAC-chd2).  This time I followed steps 1-7 and there were no problems and no warnings. 

I approve this Pull Request for merge.

**Comment by CanOfBees** [comment]
I just wanted to say that I'm not sure this should have been merged quite yet. :)

@cdeaneGit, the error that you were getting - I'd like to be sure that wasn't a result of something that I've done in this stylesheet, or with how our PHP is interacting with the XSL in the `self_transforms` directory. In any event, I'll try to do some additional testing on this tomorrow evening to see if I've introduced some weird regressive buggy-ness.

Thanks for the feedback.

**Comment by CanOfBees** [comment]
@cdeaneGit Okay, I had a few minutes to try a couple more tests. See what you think about these:
1. after following the above steps 1-7, submit a new item as userA then log out;
2. log in as thesis_manager and navigate to your new submission, go to the Manage Files tab, and *replace* the MODS data stream;
3. after replacing it, return to the Manage Files tab and *edit* the MODS dsid. There will be some errors in the XML Form, mostly due to empty elements and `name` elements that are `displayForm`-only. We're **not** worried about these errors - they're expected. I'm more concerned about the Islandora UI throwing errors related to the `trace-disciplines-list-comp.xml` file, as you saw yesterday. 
4. Make your changes to the MODS dsid and save. View the MODS dsid in your browser; i.e. `http://localhost:8000/islandora/object/utk.ir.td:$YOUR_PID/datastream/MODS/view` -- does it look right? Or mostly right? Did you see any other errors in the UI?

Thanks for your help with this!

**Comment by cdeaneGit** [comment]
Hi Bridger,

I will test again per your instructions.

I believe that all of the problems I was seeing yesterday were due to using my version of  /home/vagrant/scripts/custom_scripts/100_update_islandora_xml_forms.sh

So your instructions include a correct way of changing branches on agrantwhich I intend to ALWAYS use in the future.  Thanks for that!

Now on to testing.

cheers!
cricket!

**Comment by cdeaneGit** [comment]
Bridger requested more testing.

**Comment by cdeaneGit** [comment]
I have tested this with the new gist file and have tried to break  this is many ways, including changing the discipline value to other values on the list in trace-disciplines-list-comp.xml.  Those names worked, even when the value was changed outside of the form submission process.   But when I attempted to change the discipline to a name not on the list ("Uber Driving") the change was ignored. 

  I think this pull request is fine as longas the latest version of trace-disciplines-list-comp.xml is applied.

**Pull request merged**
