### PR TITLE
Address TRAC-378 TRAC-397

### PR DESCRIPTION
**Pull request by CanOfBees**
**JIRA Ticket**: [TRAC-378](https://jira.lib.utk.edu/browse/TRAC-378) and [TRAC-397](https://jira.lib.utk.edu/browse/TRAC-397)

# What does this Pull Request do?
This PR adds a post_process_transforms directory with three separate transforms. This PR also updates TRAC-397.

# What's new?
Three transforms that should strip empty elements from the MODS datastream.

# How should this be tested?
Copy the UTK_ir_etds_post_process.xsl transform to `sites/all/modules/islandora_xml_forms/builder/self_tranforms/` and, using the association process, link the XSL transform with an appropriate form. Check the output in the MODS datastream.

# Interested parties
@markpbaggett

### CODE REVIEW

**Comment by markpbaggett** [comment]
@CanOfBees, looking at this now. Do you want to go ahead and take the conflict since you created the p.r.?  In the meantime, I'll review.

**Comment by CanOfBees** [comment]
@markpbaggett I don't mind. Let me know when you're finished reviewing.

**Comment by markpbaggett** [comment]
If it's cool, go ahead and commit and push to your fork something to address that conflict.

**Comment by CanOfBees** [comment]
Fixed merged conflicts. Thanks for the help!

**Comment by markpbaggett** [comment]
@CanOfBees, sorry for not merging.  I got distracted for a few minutes.  I never finished testing, but we can look at what happens in tomorrow's build.

**Comment by CanOfBees** [comment]
@markpbaggett no problem; I should have paid better care to what I was doing prior to this PR. We'll see what happens with the build.

**Comment by markpbaggett** [comment]
@CanOfBees, no problem.  Not sure if you knew this, but pushing to your repo automatically assigns those new commits to the open p.r.  Therefore, no need to "pay better attention."

**Pull request merged**
