### PR TITLE
Address TRAC-534, TRAC-486, TRAC-511, and TRAC-535.

### PR DESCRIPTION
**Pull request by markpbaggett**
**JIRA Ticket**: [TRAC-535](https://jira.lib.utk.edu/browse/TRAC-535), [TRAC-511](https://jira.lib.utk.edu/browse/TRAC-511), [TRAC-486](https://jira.lib.utk.edu/browse/TRAC-486), [TRAC-534](https://jira.lib.utk.edu/browse/TRAC-534)

# What does this Pull Request do

* Address 4 JIRA tickets
* Updates the pull request template

# What's new?

* A problem with additional node creation on several nodes on update has been fixed
* Term of Address added back so that full student id can be submitted
* Order changes from Sarah Stone have been applied
* Record Info now reading correct node value

# How should this be tested?

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

*DO NOT MERGE WITHOUT TESTING!!!!*

# Interested parties
@CanOfBees @DonRichards

### CODE REVIEW

**Comment by markpbaggett** [comment]
Ugh!  There's a problem I didn't catch.  Closing and I'll reopen later today.

**Comment by markpbaggett** [comment]
Alright, reopened. Commit 1ba644a should have fixed the issue.

**Comment by CanOfBees** [comment]
@markpbaggett - 

overall looks very good, with two problems and some questions:
1. recordInfo/recordCreationDate is duplicating itself on update
2. name/namePart[@termOfAddress] should be @termsOfAddress (typo)
2. Question: is the suggestion in TRAC-511 re separated year/month OR 3 years of date of award something that needs to be implemented?
3. Question: should recordInfo/recordChangeDate use @keyDate? under the impression that @keyDate would be used for items having a withdrawn status, but that may be entirely erroneous on my part. (Based on the utk_gradthes data dictionary)
4. Question: should the recordCreationDate and recordChangeDate %value%s be generated or should we try to address this in the post-submission transform?

Thanks! I know that the questions aren't necessarily 100% specific to the linked tickets, but think that nos 1 and 2.

**Comment by markpbaggett** [comment]
1. Oof.  Let me look at that.
2. I'm an idiot.  I'll fix that.
3. I read it as a suggestion.  That adds a somewhat large level of complexity.  We're trying to capture the data as EDTF but we have to give them the data as something they'd expect (a string). The way form builder works is that you have to embed an attribute for the value you want to record in the XML record as an attribute value and then use the string as the text node.  So let's say we do what's suggested; we could have two dropdowns to get the data to the XML record like we need it.  But, how would we parse and split the data back out for edit / update?  If you have thoughts on how this would work without writing our own module, I'm all ears.
4. No, you are write.  I'll drop this.
5. This makes sense.  Can you do something with the XML processor to grab the machine date or something? If so, yes. We can create a new ticket to do this.

**Comment by markpbaggett** [comment]
Okay,  I fixed the typo with termsOfAddress and removed the recordInfo section altogether since that should be handled with post process. Because point 3 is so complicated, I didn't touch it.  Let me know if there are questions / problems prior to merge.

**Comment by markpbaggett** [comment]
Okay, this should be right now for real.  Sorry again for the false start.

**Review by CanOfBees — APPROVED** [review]
@markpbaggett - this looks great.

**Pull request merged**
