### PR TITLE
Address CON-34.

### PR DESCRIPTION
**Pull request by markpbaggett**
**JIRA Ticket**: [CON-34](https://jira.lib.utk.edu/browse/CON-34)

# What does this Pull Request do?

This adds an Islandora XML form specifically for new issues of Football Programs.

# What's new?

A new form has been added.

# How should this be tested?

* Start up your Vagrant
* Import the new form
* Associate it with your favorite content model
* Create a new object of your favorite content model and select the newly associated form
* Now edit the record and make sure it reads the values in correctly
* Now open the MODS and look at the record.  Does all look good? Are there blank nodes?

# Additional Notes:
This assumes that new records should look like the old ones.  The data model hasn't changed at all. 

Also, one of the dates will need to be handled in the post-process transform.  I'll create a separate ticket and pull request for that.

# Interested parties
@mlhale7

### CODE REVIEW

**Review by mlhale7 — COMMENTED** [review]
@markpbaggett - In terms of functionality and matching the data that currently exists, this form is good and is ready to be approved. Thanks for making it. I think I'll need to do some work on the instructions to make this easier to use for those entering the data. In particular, I need to look at the tags to provide additional instruction on how to form these consistently.

There are a lot of things about this collection that do not match the metadata of the rest of our collections. We may not be able to address this now, but I'll note the issues here. In football programs we do not invert names and we aren't including URIs. I noticed that physicalLocation is listed at the Libraries generally rather than special collections. On this note, I am hoping to hear from Alesha on the AR collection these programs are associated with so we can include it in the metadata. The current creator value we are writing in (University of Tennessee (campus)) also isn't a thing. I think it's attempting to be "University of Tennessee (Knoxville campus) - http://id.loc.gov/authorities/names/n80003887 , but this is only correct for names up to 1968. We won't want to write either in going forward. Finally, I would like to add one hidden subject (<subject authority="naf" valueURI="http://id.loc.gov/authorities/names/n90646627"><name><namePart>Tennessee Volunteers (Football team)</namePart></name></subject>). Currently this isn't present in any of the metadata records, but it would be great to write it to all of them. We don't use any of the existing blanket subject headings (e.g. "University of Tennessee (Knoxville campus) -- Football -- Periodicals"), but none of these resolve in https://id.loc.gov so I'd have to rework them anyways.

I can update the form you created with some instructions (for the tag field in particular and adding a blanket subject heading) and attach it here. If we can address some of the messiness of the metadata that would help going forward, but I know this isn't the main objective at hand. I can work on a data dictionary for this if we want.

**Comment by markpbaggett** [comment]
@mlhale7 thanks for the feedback. As far as workflow goes, the person who opens the pull request should address everything that needs to happen prior to approval and merge. Therefore, I need to grasp what this needs to do and build it in.

I'm having a little trouble digesting what all needs to happen before this can be approved and merged. Could you break out your feedback out into a bulleted list?  It seems to me that we'd probably want to handle some of the things you suggest here with a post-process transform or think about modifying the data model in order to make the form a little more inter-operable.

**Comment by mlhale7** [comment]
@markpbaggett - below are my suggestions for this form and the football metadata. Let me know what's possible to address now and what needs to wait until later on. Sorry if any conditional language below makes what I'm saying confusing. I'm not sure what we'll want to wait to address.

**Data Remediation** 

- Remediate Creator node in existing data for programs prior to and including 1968 change to: `<name authority=”naf” valueURI=“http://id.loc.gov/authorities/names/no2018063181”><namePart>University of Tennessee (Knoxville campus). Department of Athletics</namePart></name>`
- For programs post 1968 change to: `<name authority=”naf” valueURI=“http://id.loc.gov/authorities/names/no2018064251”><namePart>University of Tennessee, Knoxville. Department of Athletics</namePart></name>`
- Remediate topical subject headings to those that will resolve and are accurate
  - Replace “Imprints, Tennessee -- Knoxville -- 1904.” with “College sports” - http://id.loc.gov/authorities/subjects/sh85028338
  - Replace “University of Tennessee (Knoxville campus) -- Football -- Periodicals.” with “Football” - http://id.loc.gov/authorities/subjects/sh85050405

**Changes to Form**
- Add in a blanket name subject: `<subject authority=”naf” valueURI=”http://id.loc.gov/authorities/names/n90646627”><name><namePart>Tennessee Volunteers (Football team)</namePart></name></subject>`
- Make Creator node be: `<name authority=”naf” valueURI=“http://id.loc.gov/authorities/names/no2018064251”><namePart>University of Tennessee, Knoxville. Department of Athletics</namePart></name>`
- Add additional instructions for Tag fields (either in form or on Wiki) to ensure that values are consistently entered. I'd suggest three different tag fields so that instructions can refer to the different types of tags (if all tag types are needed). A list of existing tag values is
[attached](https://github.com/utkdigitalinitiatives/utk_isl_xml_forms/files/2581449/fbpro_tag.txt)
   - Coach Tag: Instructions could be something like, “Add Coach along the years served in this capacity - e.g. (starting year - ending year) First name Last name. For current programs use the following value: (2018-) Jeremy Pruitt”
   - Coach Tag: Add default value of “(YYYY-YYYY) Fname Lname”
   - Type of publication/program: Have a drop-down list with all of the options that can be used (Spring Games, Football Guides, Postseason, Guides
   - Year: I don’t think we need this tag type since the date is entered into the metadata. I think we could make a separate dateCreated that is just the year to make browsing easier.
- Add the following text to the general subject field to encourage students to use LoC controlled vocabularies: “Use `<a href="https://id.loc.gov">https://id.loc.gov</a>` to use a controlled subject term if possible. Copy and paste the term directly from the online record.”
- If we remediate the existing subjects, add both “College sports” and “Football” as hidden blanket subjects in the form

**Comment by markpbaggett** [comment]
@mlhale7, great.  I'll get these started.

**Comment by markpbaggett** [comment]
@mlhale7, sorry just getting back to this.

So the data remediation bit really needs to happen in another ticket and outside this pull request.  Are you planning to do that in another ticket, or is that something you need me to do?

**Comment by mlhale7** [comment]
@markpbaggett - I edited my previous comment to remove the archival collection information. Talking with Alesha, this collection is only individually cataloged and is not part of a MS collection.

I also went ahead and created a ticket for the remediation work ([META-6](https://jira.lib.utk.edu/browse/META-6)). I would agree that it's separate, but it does need to be done before we can finish this out. I think this is my responsibility as part of the migrations, so I've assigned the task to myself. I'd definitely like to talk more about ways that I can approach this work.

**Comment by markpbaggett** [comment]
@mlhale7 , the following things have been done:

1. This subject is now blanketed but not read on edits: <subject authority=”naf” valueURI=”http://id.loc.gov/authorities/names/n90646627”><name><namePart>Tennessee Volunteers (Football team)</namePart></name></subject>
2. This is now the creator node: <name authority=”naf” valueURI=“http://id.loc.gov/authorities/names/no2018064251”><namePart>University of Tennessee, Knoxville. Department of Athletics</namePart></name>  It shows in form, but is not editable.
3. Something like this has been done:  Add the following text to the general subject field to encourage students to use LoC controlled vocabularies: “Use <a href="https://id.loc.gov">https://id.loc.gov</a> to use a controlled subject term if possible. Copy and paste the term directly from the online record.” There is a bug with Add that makes default text not show.
4. These terms are now blanketed but not selected on edits:  “College sports” and “Football” 

## This is not done
The tagging stuff is complicated, and if we want to do this, I'd like to see rememdiation done first.  That's because we can't keep the same data model and have forms work with dropdowns.  You'd need separate Xpaths for the reads, or you'd have to write a selector that ignored lots of variables.  Managing these lists would become a job (it's going to be a job regardless, but doing this now would make the job even more crazy).

**Review by mlhale7 — CHANGES_REQUESTED** [review]
Hi Mark - I've got a few edits:

- Make the creator node hidden (I think there's no reason to show it if we aren't going to edit it)
- Reorder the nodes so that the last tags are: relatedItem (Project), languageOfCataloging, recordInfo, recordOrigin, accessCondition (in that order).
- languageOfCataloging is getting written in twice upon updating (you need to add Read)
- entire recordInfo tag is getting written in twice upon updating (you need to add Read, maybe break out into separate nodes to deal with the complexity)

Sorry for not catching the update duplicates before.

**Comment by markpbaggett** [comment]
@mlhale7 thanks for the feedback.  I'll work on this today.

**Comment by markpbaggett** [comment]
@mlhale7 I did most of what you asked. Some of the node reordering requests involved nodes embedded in other nodes, so I did my best to try to do what you asked while keeping things valid.

**Comment by mlhale7** [comment]
@markpbaggett - All of the fields that were getting duplicated have been corrected (thanks!). I did notice one random issue. If you enter two tags initially, if you add another field when you update you need to fill two blanks (or just fill one and have an empty node). See the image for more info.
doubletags

**Comment by markpbaggett** [comment]
@mlhale7 you are right, but there really isn't a solution other than to drop fieldpanes and panels for this and try something else.  Even then, I'm not sure it would work.  I don't get what's happening here, but it's a form in form builder or another helper module.  We're seeing it here because fieldpane doesn't get a create value.

My thoughts:  even though it shows up twice or three or four times, is it really a big deal?  If those other four are ignored, the node will be blank, and we will have a XSL transform run against it to remove blank nodes.

I really feel strongly that this is a bug that will be difficult and expensive to address, and I wonder if we really it's truly worth working on.

**Review by mlhale7 — APPROVED** [review]
@markpbaggett - I'd agree that this would be difficult to fix technically, but I felt it was important to note. I feel that it could be addressed by simply making those inputting data aware of this issue. If I become aware of any better way to address this as I work through the rest of the forms, I will let you know.

**Comment by markpbaggett** [comment]
@mlhale7 what if we simply put a note about this in the description of tags in the form?

**Comment by mlhale7** [comment]
@markpbaggett - I think this is a good idea. The difficulty is that I think the person entering the data should be able to initially enter two tags (or however many are needed). Can we put the instructions in the context of updating? AKA - "Don't update tags field if more than the necessary number of blanks appears."

**Comment by markpbaggett** [comment]
How about that?

**Comment by markpbaggett** [comment]
> @markpbaggett - I think this will work. I highly doubt we'll do much updating (this is really for initial entry), but it's good to be prepared. Will we be able to delete empty tags after updates assuming the additional tag fields are ignored?

@mlhale7,You have to write and associate a post-process transform to do this, but yes.

**Review by mlhale7 — APPROVED** [review]

**Comment by mlhale7** [comment]
@markpbaggett - I don't seem to have permission to merge now for whatever reason, but this is ready to go.

**Pull request merged**
